### ISSUE TITLE
Child BelongsTo in Form leads to undefined ajax request

### ISSUE THREAD

**Issue by Crazymodder** [shivanshrajpoot/nova-create-or-add#1]
Hi,

First thanks for your great package.

If I add a BlongsTo Field to the create Form and get a wrong ajax request.

My Example
Post belongs To User. Post belongs to Category. So on User Ressource I add

NovaCreateOrAdd::make('Post')

But the belongsTo in the New Post Form now generates wrong ajax request to select a category

nova-api/undefined/associatable/post?first=false&search=First Post&withTrashed=false

correct would be:
nova-api/**category**/associatable/post?first=false&search=First Post&withTrashed=false

**Comment by shivanshrajpoot** [comment]
I think you have misinterpreted, the use case for this package, correct would be, You should be able to create or use existing one **Category** / **User** on the **Post** form rather than creating each one on their resource page. So please use it on the Post resource,  NovaCreateOrAdd::make('User'), NovaCreateOrAdd::make('Category').
